name: datascience
channels:
- conda-forge
dependencies:
- python=3.9
- pip==22
- pip:
    - numpy>=1.23.3
    - matplotlib>=3.6.0
    - pandas>=1.5.1
    - plotly>=5.11.0
    - prophet>=1.1.1
    - pmdarima>=2.0.1
    - scikit-image>=0.19.3
    - statsmodels>=0.13.2
    - black>=22.6.0                         #dev
    - ipython>=8.5.0                        #dev
    - notebook>=6.4.12                      #dev
    - openpyxl>=3.0.10                      #dev
    - pillow>=9.2.0                         #dev
    - setuptools>=65.5.0                    #dev
